"""
The assembled Core A′: all seven modules, every counter wired (spec §11 phase 13b).

Phase 11's full compositions stripped transcription's and decay's counters,
because their CTP and UTP debits could not compose until phase 13a gave a
chemostat an ownerless path. This is the composition with nothing stripped, and
the one place it is written down, so the tests and the Slurm drivers cannot
drift apart on what "the assembled model" means.
"""

"""
    COREA_CYCLE_S

One cell cycle, 6,300 s — the horizon every full-cycle check runs over. Spec §3
forbids shortening it: 144 s of the adenylate pool looked fine before the dead
end was found.
"""
const COREA_CYCLE_S = CHARGING_CYCLE_S

"""
    COREA_SMOOTHING_WIDTH

The width, in particles, of the smoothed drain phase 14c puts on every consumer
counter (spec §11 task 14c.4, §12 2026-09-28 planning B): one particle.

Under `clip = :smoothed` the pool a debit leaves is `w·softplus((pool − accrued)/w)`
rather than `max(pool − accrued, 0)`. The two differ by at most `w·ln 2`, at the
kink, and by `w·exp(−gap/w)` a gap away. One particle is the resolution the count
round trip already works at, so the smoothing acts below the model's own quantum:
at published parameters it moves at most 0.69 particles on each clipped drain.
The price is a derivative that bends over about one particle. This is ours, not
the published model's, and `reduction_report` says so.
"""
const COREA_SMOOTHING_WIDTH = 1.0

"""
    corea_models(; metered = false, smoothing = nothing) -> Vector{AbstractSubModel}

The seven Core A′ modules as the assembled model composes them. Glycolysis and
recycling read their enzyme concentrations from translated protein counts
(`enzymes = :translated`, spec §11 phase 11a); transcription, decay and
translation carry every deferred counter they declare.

`metered = true` swaps in [`MeteredPtsTransport`](@ref), which integrates
glucose uptake and lactate export into two extra states that nothing reads.
It is the instrument check 2's carbon balance needs (spec §11 task 14.3).

`smoothing = nothing` is the published drain: each consumer counter floors its
pool at zero and carries the shortfall. A width in particles — phase 14c's is
[`COREA_SMOOTHING_WIDTH`](@ref) — declares every counter `clip = :smoothed` at
that width instead, which is the model a gradient-based sampler differentiates
(spec §8 K5). Synthetic data is generated by the clamped one.
"""
function corea_models(; metered::Bool = false,
                      smoothing::Union{Nothing, Real} = nothing)
    drain = smoothing === nothing ? (clip = :clamped_deficit_carried, smoothing = nothing) :
                                    (clip = :smoothed, smoothing = Float64(smoothing))
    return AbstractSubModel[
        CentralGlycolysis(enzymes = :translated),
        metered ? MeteredPtsTransport() : PtsTransport(),
        NucleotideRecycling(enzymes = :translated),
        TrnaCharging(),
        CoreATranscription(; drain...),
        CoreATranscriptDecay(; drain...),
        CoreATranslation(; drain...),
    ]
end

"""
    build_corea(; tspan = (0.0, COREA_CYCLE_S), metered = false, smoothing = nothing,
                kwargs...) -> HandshakeDriver

Build the assembled Core A′ over one full cycle, in completeness mode: the build
fails if any registry dynamic state is unowned or any moiety is stranded (spec
§11 task 13.1). The remaining keywords are the hybrid driver's
([`build_problem`](@ref)); the solver and tolerances default to the pinned
Rodas5P at `abstol = 1e-10`, `reltol = 1e-8` of spec §3. `metered` and
`smoothing` are [`corea_models`](@ref)'s.
"""
build_corea(; tspan = (0.0, COREA_CYCLE_S), metered::Bool = false,
            smoothing::Union{Nothing, Real} = nothing, kwargs...) =
    build_problem(corea_models(; metered, smoothing); tspan, complete = true, kwargs...)

export COREA_CYCLE_S, COREA_SMOOTHING_WIDTH, corea_models, build_corea
