# Spec §11 task 3.8: measure what the 1 s handshake costs.
#
# Runs the phase-3 toy — one jump gene-expression module and one ODE metabolite
# module, exchanging state every simulated second — and reports seconds of
# wall-clock per second of simulated time, together with the extrapolation to a
# full 6,300 s cell cycle that kill criterion K1 is stated against.
#
# **The extrapolation is a floor, not an estimate of Core A′.** The toy is two
# modules, one gene and two metabolite states; Core A′ is seven modules,
# seventeen genes and thirty-two states. A pass here is necessary and not
# sufficient, and K1 is actually decided by task 13.7 at full scale. The report
# says so in its own text so the number cannot travel without the caveat.
#
# Usage: julia --project dev/scripts/bench_handshake.jl

using InferCell
using Random
using Printf
using Dates

include(joinpath(@__DIR__, "..", "..", "test", "contribution_test_models.jl"))
include(joinpath(@__DIR__, "..", "..", "test", "jump_test_models.jl"))
include(joinpath(@__DIR__, "..", "..", "test", "hybrid_test_models.jl"))

const CYCLE = 6300.0        # s, the published cell cycle
const BUDGET = 10.0         # s of wall-clock per trajectory, spec §8 K1

# Best of `reps` after one warm-up, matching dev/scripts/bench_rhs_containers.jl:
# the minimum is the honest estimator for a timing floor on a shared node.
function time_run(build, n_steps; reps = 3)
    d = build()
    run_handshake!(d, min(n_steps, 10))          # warm-up: compile for these types
    best = Inf
    for _ in 1:reps
        d = build()
        best = min(best, @elapsed run_handshake!(d, n_steps))
    end
    return best
end

build_toy(; kcat = 0.0) = () -> begin
    Random.seed!(20260904)
    build_problem([ToyPool(kcat = kcat), ToyExpression()]; tspan = (0.0, CYCLE))
end

# Provenance is captured *before* the measurements, not after. Reading
# `git rev-parse` at write time stamps whatever HEAD happens to be when the run
# finishes, which on a long job can be a commit made after the code was loaded —
# the artefact then names source the measurement never saw.
const COMMIT = strip(read(`git rev-parse --short HEAD`, String))
const DIRTY = !isempty(strip(read(`git status --porcelain -- src test Project.toml Manifest.toml dev/scripts/bench_handshake.jl`, String)))

rows = NamedTuple[]
for horizon in (60, 300, 600)
    for (label, kcat) in (("frozen pool (kcat = 0)", 0.0), ("live rate law", 30.0))
        secs = time_run(build_toy(kcat = kcat), horizon)
        per_sim_s = secs / horizon
        push!(rows, (horizon = horizon, label = label, wall = secs,
                     per_sim_s = per_sim_s, cycle = per_sim_s * CYCLE))
    end
end

# The verdict is taken on the slowest configuration measured, since that is the
# one a real module set most resembles.
worst = maximum(r -> r.cycle, rows)
verdict = worst <= BUDGET ? "PASS" : "FAIL"

commit, dirty = COMMIT, DIRTY
jobid = get(ENV, "SLURM_JOB_ID", "not under Slurm")

io = IOBuffer()
println(io, "# The 1 s handshake: wall-clock (spec task 3.8)")
println(io)
println(io, "Generated by `dev/scripts/bench_handshake.jl` at commit $commit",
        dirty ? " (WARNING: tree dirty)" : "",
        ", Slurm job $jobid, on $(gethostname()), $(Dates.now()), Julia $(VERSION).")
println(io)
println(io, "Regenerate with `sbatch dev/scripts/bench_handshake.slurm`.")
println(io)
println(io, "Toy: `ToyPool` (2 ODE states, stiff `Rodas5P`, abstol 1e-10, reltol 1e-8) ")
println(io, "composed with `ToyExpression` (3 jump states, 3 reactions), exchanging ")
println(io, "every 1.0 s under the `:fractional_carry` rounding policy.")
println(io)
println(io, "| horizon (s) | configuration | wall-clock (s) | s per simulated s | extrapolated to 6,300 s |")
println(io, "|---|---|---|---|---|")
for r in rows
    @printf(io, "| %d | %s | %.3e | %.3e | %.3f |\n",
            r.horizon, r.label, r.wall, r.per_sim_s, r.cycle)
end
println(io)
@printf(io, "**Verdict against K1's %.0f s budget: %s** — worst extrapolation %.3f s per 6,300 s trajectory.\n",
        BUDGET, verdict, worst)
println(io)
println(io, """
**This number is a floor, not Core A′'s cost.** The toy carries one gene and two
metabolite states against Core A′'s seventeen and thirty-two, and its ODE block
is two equations rather than twenty-two reactions across four modules. The cost
of the real composition can only be larger. A pass here is therefore necessary
and not sufficient: it says the *architecture* does not carry a fatal per-
handshake overhead, which is what phase 3 exists to establish. K1 is decided by
task 13.7, at full scale.

What the measurement does bound honestly is the per-handshake overhead of the
exchange itself, which is the quantity the mechanism choice of task 3.1 was
made on: the frozen-pool row runs the same 1 s loop with a zero derivative, so
the gap between the two rows is integration and the frozen row is very nearly
the handshake alone.""")

s = String(take!(io))
print(s)
write(joinpath(@__DIR__, "bench_handshake_result.md"), s)
