# Spec §11 phase 14a: the balance checks on the assembled Core A′, at full scale.
#
# 14.1  Check 0: the rounding signature on the assembly, under all three policies.
# 14.2  Check 1: the first negative state and time, and the tightest margin.
# 14.3  Check 2: carbon closure, the homolactic ratio, and the export mutation.
# 14.4  Check 3: redox, at composition scope.
# 14.5  Check 4: adenylate and guanylate over a full cycle, and the kinase-removed
#       threshold crossing.
# 14.6  Check 4b: phosphate, closed through the chemostats and the transcripts.
# 14.7  Check 5: the four carriers, up to what translation adds.
# 14.10 One mutation per check.
#
# Every closure is whole-cell and in particles (src/organisms/coreA/validation.jl).
# The tolerance ladder runs over six decades ending at the pinned pair, with
# every rung reported, as spec §3 requires of a roundoff-level residual.
#
# Usage: julia --project dev/scripts/corea_validation.jl
# Regenerate: sbatch dev/scripts/corea_validation.slurm

using InferCell
using Printf
using Dates
using Random
using Statistics: mean

include(joinpath(@__DIR__, "..", "..", "test", "nucleotide_test_models.jl"))
include(joinpath(@__DIR__, "..", "..", "test", "corea_validation_doubles.jl"))

const COMMIT = strip(read(`git rev-parse --short HEAD`, String))
const DIRTY = !isempty(strip(read(`git status --porcelain -- src test dev/scripts`, String)))
const JOB = get(ENV, "SLURM_JOB_ID", "none")
# SMOKE=1 shrinks every horizon so a code error surfaces in minutes, not hours.
# A smoke run is not a result: its file says so and nothing may quote it.
const SMOKE = get(ENV, "SMOKE", "0") == "1"
const CYCLE = SMOKE ? 120 : round(Int, COREA_CYCLE_S)
const SEED = 1410
const MUT_S = SMOKE ? 60 : 600        # mutations fail fast; a full cycle is not needed
const PINNED = (1e-10, 1e-8)
# Six decades ending at the pinned pair, then one rung tighter for the fall.
const LADDER = SMOKE ? [PINNED, (1e-11, 1e-9)] :
    [(1e-4, 1e-2), (1e-5, 1e-3), (1e-6, 1e-4), (1e-7, 1e-5), (1e-8, 1e-6),
     (1e-9, 1e-7), PINNED, (1e-11, 1e-9)]
const KINASE_S = SMOKE ? 60 : 1200
const UNCLAMPED_S = CYCLE              # 13b's first GTP clip was at 953 s, seed-dependent

out = IOBuffer()
p(args...) = (println(out, args...); println(args...); flush(stdout))
fmt(x) = @sprintf("%.3g", x)

p("# Phase 14a: the balance checks on the assembled Core A′", SMOKE ? " — SMOKE RUN, NOT A RESULT" : "")
p()
p("Generated by `dev/scripts/corea_validation.jl` at commit $COMMIT",
  DIRTY ? " (tree dirty)" : "", ", Slurm job $JOB, on $(gethostname()), ",
  "$(now()), Julia $VERSION. Seed $SEED, set before every build.")
p()
p("Regenerate with `sbatch dev/scripts/corea_validation.slurm`.")
p()

function run_cycle(models; n = CYCLE, abstol = PINNED[1], reltol = PINNED[2],
                   rounding = :fractional_carry, seed = SEED, tspan_end = n)
    Random.seed!(seed)
    d = build_problem(models; tspan = (0.0, Float64(tspan_end)), complete = true,
                      abstol, reltol, rounding)
    Random.seed!(seed)
    local vrun
    wall = @elapsed vrun = validation_run!(models, d, n)
    return d, vrun, wall
end

names_of(vrun) = [m.name for m in vrun.moieties]
maxres(vrun, name) = maximum(abs, closure_residual(vrun, name))

# ---------------------------------------------------------------------------
p("## The pinned full cycle")
p()
ms = validation_models()
tb = @elapsed d, vrun, wall = run_cycle(ms)
p(@sprintf("Built and ran 6,300 handshakes at (%g, %g): %.1f s including build and compile, %.1f s of it the run.",
           PINNED..., tb, wall))
p()
p("| moiety | max residual (particles) | final residual | tol_C (particles) | residual / tol_C | RHS gate | n terms | max ulps per evaluation | max residual / γₙ |")
p("|---|---|---|---|---|---|---|---|---|")
gates = Dict{Symbol, Any}()
for name in names_of(vrun)
    r = closure_residual(vrun, name)
    g = rhs_gate(ms, d, vrun, name)
    gates[name] = g
    b = moiety_bound(vrun, name)
    p("| $name | $(fmt(maximum(abs, r))) | $(fmt(last(r))) | $(fmt(b)) | $(fmt(maximum(abs, r) / b)) | $(g.gate) | $(g.n) | $(fmt(g.max_ulps)) | $(fmt(g.max_gamma)) |")
end
p()
tot0 = Dict(n => first(vrun.totals[n]) for n in names_of(vrun))
p("Initial whole-cell totals, in particles: ",
  join(("$n $(fmt(tot0[n]))" for n in names_of(vrun)), ", "), ".")
p()

p("### Check 0: the carried remainder")
p()
p("Largest carried remainder over the cycle: $(fmt(vrun.max_remainder)) particle ",
  "(fractional carry keeps it within ±0.5).")
p()

p("### Check 1: non-negativity")
p()
v = first_negative(vrun)
bounds = [state_bound(vrun, i) for i in eachindex(vrun.ode_names)]
mins = [minimum(u[i] for u in vrun.ode) for i in eachindex(vrun.ode_names)]
margins = mins .+ bounds
k = argmin(margins)
p(v === nothing ? "No state falls below the negative of its integrator bound." :
  "First violation: `$(v.species)` = $(v.value) at t = $(v.t) s, bound $(v.bound).")
p("Tightest margin: `$(vrun.ode_names[k])`, minimum $(fmt(mins[k])) mM against bound $(fmt(bounds[k])) mM. ",
  "States touching exactly zero: ", join(("`$(vrun.ode_names[i])`" for i in eachindex(mins) if mins[i] == 0), ", "), ".")
p("Jump states' minimum: $(minimum(vrun.jump_min)).")
p()

p("### Check 2: carbon")
p()
ca = carbon_accounts(vrun)
p(@sprintf("Glucose in %.6g, lactate out %.6g, lactate formed %.6g, glucose consumed %.6g particles.",
           ca.glucose_in, ca.lactate_out, ca.lactate_formed, ca.glucose_consumed))
p(@sprintf("Homolactic ratio %.12f (departure from 2: %.3g). Exported fraction of lactate formed: %.6f.",
           ca.homolactic, ca.homolactic - 2, ca.exported))
ie = findfirst(==(:M_lac__L_e), vrun.ode_names)
ratio = 1e5
lac_e_start = first(vrun.ode)[ie] * ratio * first(vrun.factor)
lac_e_now = last(vrun.ode)[ie] * ratio * last(vrun.factor)
lac_e_fixed = last(vrun.ode)[ie] * ratio * first(vrun.factor)
p(@sprintf("External lactate referred to the medium: lac_e·R·factor is %.6g particles at the final factor and %.6g at the initial one, against %.6g exported (the meter). Relative gaps %.3g and %.3g.",
           lac_e_now - lac_e_start, lac_e_fixed - lac_e_start, ca.lactate_out,
           (lac_e_now - lac_e_start) / ca.lactate_out - 1, (lac_e_fixed - lac_e_start) / ca.lactate_out - 1))
p()

p("### Check 4: the interval")
p()
p("The run ends at t = $(last(vrun.t)) s after $(vrun.n_restarts) handshakes.")
p()

# ---------------------------------------------------------------------------
p("## The tolerance ladder")
p()
p("Every rung is a full cycle at the same seed. The residual is the largest whole-cell closure residual over the cycle, in particles.")
p()
ladder = Dict{Tuple{Float64, Float64}, ValidationRun}()
walls = Dict{Tuple{Float64, Float64}, Float64}()
for rung in LADDER
    try
        if rung == PINNED
            ladder[rung] = vrun; walls[rung] = wall
        else
            _, r, w = run_cycle(ms; abstol = rung[1], reltol = rung[2])
            ladder[rung] = r; walls[rung] = w
        end
    catch err
        p("Rung $(rung): failed — ", sprint(showerror, err)[1:min(end, 300)])
    end
end
rungs = [r for r in LADDER if haskey(ladder, r)]
p("| moiety | ", join(("($(r[1]), $(r[2]))" for r in rungs), " | "), " |")
p("|---|", repeat("---|", length(rungs)))
for name in names_of(vrun)
    p("| $name residual | ", join((fmt(maxres(ladder[r], name)) for r in rungs), " | "), " |")
    p("| $name / tol_C | ", join((fmt(maxres(ladder[r], name) / moiety_bound(ladder[r], name)) for r in rungs), " | "), " |")
end
p("| run wall-clock (s) | ", join((@sprintf("%.1f", walls[r]) for r in rungs), " | "), " |")
p()
tight = (PINNED[1] / 10, PINNED[2] / 10)
if haskey(ladder, tight)
    p("Fall from the pinned pair to one decade tighter (≥5 is the fall; flat is the exception):")
    p()
    for name in names_of(vrun)
        a, b = maxres(ladder[PINNED], name), maxres(ladder[tight], name)
        p("- $name: $(fmt(a)) → $(fmt(b)), ratio $(fmt(a / max(b, eps())))")
    end
    p()
end

# ---------------------------------------------------------------------------
p("## Check 0 on the assembly: three rounding policies")
p()
p("Each policy runs a full cycle at the pinned tolerances. The residual at 630 and 6,300 handshakes tells a bounded signature from √N or linear growth.")
p()
p("| policy | seed | moiety | residual at 630 | residual at 6,300 | ratio |")
p("|---|---|---|---|---|---|")
for (policy, seeds) in ((:fractional_carry, [SEED]), (:deterministic, [SEED]),
                        (:stochastic, SEED .+ (0:4)))
    for s in seeds
        r = (policy, s) == (:fractional_carry, SEED) ? vrun :
            run_cycle(ms; rounding = policy, seed = s)[2]
        for name in (:adenylate, :guanylate, :phosphate, :carrier_ptsI)
            res = closure_residual(r, name)
            a, b = abs(res[min(631, end)]), abs(res[end])
            p("| $policy | $s | $name | $(fmt(a)) | $(fmt(b)) | $(fmt(b / max(a, eps()))) |")
        end
    end
end
p()

# ---------------------------------------------------------------------------
p("## Check 4: the kinase removed")
p()
km = validation_models(recycling = kinase_removed())
dk, rk, wk = run_cycle(km; n = KINASE_S)
ia = findfirst(==(:M_atp_c), rk.ode_names)
atp0 = first(rk.ode)[ia]
kc = findfirst(u -> u[ia] < 0.01 * atp0, rk.ode)
p("ATP starts at $(fmt(atp0)) mM. ",
  kc === nothing ? "It does not fall below 1% within $KINASE_S s." :
  "It first falls below 1% of that at t = $(rk.t[kc]) s, against the scoping note's 144 s for a constant drain.")
p("ATP at 60, 144, 300, 600, 1200 s: ",
  join((fmt(rk.ode[k + 1][ia]) for k in (60, 144, 300, 600, 1200) if k <= KINASE_S), ", "), " mM.")
for name in (:adenylate, :guanylate, :phosphate)
    p("- $name closes with the kinase removed: max residual $(fmt(maxres(rk, name))) particles, tol_C $(fmt(moiety_bound(rk, name))).")
end
p()

# ---------------------------------------------------------------------------
p("## Mutations: each check fails, naming its quantity")
p()
p("Each mutant runs $MUT_S handshakes at the pinned tolerances. The table gives every moiety's residual over its own tol_C; a check fails where the ratio exceeds one.")
p()
mutants = [
    ("redox: GAPD draws two NAD⁺", validation_models(glycolysis = glycolysis_mutation(:R_GAPD, :M_nad_c, 2)), :redox),
    ("carbon: LDH makes two lactate", validation_models(glycolysis = glycolysis_mutation(:R_LDH_L, :M_lac__L_c, 2)), :carbon),
    ("adenylate: ADK1 makes one ADP", validation_models(recycling = MutatedRecycling(:adk1_adp_coefficient; enzymes = :translated)), :adenylate),
    ("guanylate: GK1 creates a GDP", validation_models(recycling = MutatedRecycling(:gk1_gdp_created; enzymes = :translated)), :guanylate),
    ("phosphate: PPA releases one phosphate", validation_models(recycling = MutatedRecycling(:ppa_phosphate_coefficient; enzymes = :translated)), :phosphate),
    ("ptsH: GLCpts1 creates phospho-HPr", validation_models(pts = MeteredCarrierLeak()), :carrier_ptsH),
    ("boundary: GAPD's counters charge ten A for ten U", validation_models(transcription = CoreATranscription(genes = shifted_genes(:JCVISYN3A_0607; A = 10, U = -10))), :adenylate),
]
p("| mutation | intended | ", join(string.(names_of(vrun)), " | "), " |")
p("|---|---|", repeat("---|", length(names_of(vrun))))
for (label, mm, intended) in mutants
    try
        local rm
        tm = @elapsed (rm = run_cycle(mm; n = MUT_S)[2])
        p("| $label ($(round(Int, tm)) s) | $intended | ",
          join((fmt(maxres(rm, n) / moiety_bound(rm, n)) for n in names_of(rm)), " | "), " |")
    catch err
        p("| $label | $intended | failed to run: ", replace(sprint(showerror, err)[1:min(end, 200)], "\n" => " "), " |")
    end
end
p()
p("Check 1's mutation: translation's debits unclamped, so a clip takes a pool negative.")
_, rn, _ = run_cycle(validation_models(translation = CoreATranslation(clip = :unclamped)); n = UNCLAMPED_S)
vn = first_negative(rn)
p(vn === nothing ? "No state went negative in $UNCLAMPED_S s." :
  "First violation: `$(vn.species)` = $(fmt(vn.value)) mM at t = $(vn.t) s, bound $(fmt(vn.bound)).")
p()
p("Check 2's export mutation: the exporter's permeability set to zero.")
nx = validation_models(pts = MeteredPtsTransport(PtsTransport(free = [:p_lact2r])))
dx = build_problem(nx; tspan = (0.0, Float64(MUT_S)), complete = true)
# The ODE block's parameter layout is first-seen-by-name over its modules.
pnames = unique([q.name for m in nx if formalism(m) === :ode
                 for q in model_free_params(parameters(m))])
px = findfirst(==(:p_lact2r), pnames)
length(pnames) == length(dx.ode.p) || error("parameter layout mismatch")
dx.ode.p[px] = 0.0
Random.seed!(SEED)
rx = validation_run!(nx, dx, MUT_S)
cx = carbon_accounts(rx)
il = findfirst(==(:M_lac__L_c), rx.ode_names)
slope = (last(rx.ode)[il] - first(rx.ode)[il]) / MUT_S
p(@sprintf("Cytosolic lactate rises %.4g mM/s, heading for %.0f mM over a cycle at this rate (lactate_export_rationale records ~691 mM). Exported fraction %.3g; carbon closure residual / tol_C %.3g.",
           slope, first(rx.ode)[il] + slope * CYCLE, cx.exported,
           maxres(rx, :carbon) / moiety_bound(rx, :carbon)))
p()

write(joinpath(@__DIR__, "corea_validation_result.md"), String(take!(out)))
println("wrote dev/scripts/corea_validation_result.md")
