# Spec §11 tasks 13.5 and 13.7: the assembled Core A′ over one full cycle.
#
# 13.5. `build_corea()` — all seven modules, every counter wired, built in
#       completeness mode — run for 6,300 handshakes at the pinned Rodas5P and
#       tolerances. The hook throws on any non-success solver retcode, so a
#       cycle that completes is a cycle with no solver failure.
# 13.7. Wall-clock per trajectory at full scale: build, the first handshake
#       (which compiles), and the remaining 6,299, against phase 3's toy
#       extrapolation and phase 11's partial seven-module reading.
#
# It also remeasures what phase 11's partial run reported before phase 13a's
# product credits existed (spec §12, 2026-09-24 E and F): when each counter
# first clips and how often, the GTP and charged-tRNA pools, whether the
# charged pool is read at its floor at rebuild instants (R11), and the protein
# fold change. Those are recorded here; their verdicts are phase 14's.
#
# The drain granularity is the published 1 s unless DRAIN_S is set, which is
# how the chosen granularity of task 13.4 is rerun here.
#
# Usage: julia --project dev/scripts/corea_full_cycle.jl
# Regenerate: sbatch dev/scripts/corea_full_cycle.slurm

using InferCell
using Printf
using Dates
using Random
using Statistics: median

const COMMIT = strip(read(`git rev-parse --short HEAD`, String))
const DIRTY = !isempty(strip(read(`git status --porcelain -- src test dev/scripts`, String)))
const JOB = get(ENV, "SLURM_JOB_ID", "none")
const DRAIN = parse(Float64, get(ENV, "DRAIN_S", "1.0"))
const CYCLE = round(Int, COREA_CYCLE_S)
const SEED = 1310
const N = corea_particles_per_mM()
# Phase 3's toy extrapolation and phase 11's partial reading, for comparison.
const TOY_S_PER_CYCLE = 0.019           # dev/scripts/bench_handshake_result.md
const PHASE11_S_PER_CYCLE = 17.9        # job 17131232, without transcription's counters

out = IOBuffer()
p(args...) = (println(out, args...); println(args...); flush(stdout))

p("# The assembled Core A′ over one full cycle (spec tasks 13.5, 13.7)")
p()
p("Generated by `dev/scripts/corea_full_cycle.jl` at commit $COMMIT",
  DIRTY ? " (tree dirty)" : "", ", Slurm job $JOB, on $(gethostname()), ",
  "$(now()), Julia $VERSION.")
p()
p("Regenerate with `sbatch dev/scripts/corea_full_cycle.slurm`.")
p()

ms = corea_models()
tbuild = @elapsed d = build_corea(drain_interval = DRAIN)
p("## 13.5 — the build and the solver")
p()
p("`build_corea()` built in completeness mode: no unowned state, no dead end, ",
  "$(length(resolve_coupling(ms).edges)) declared edges and ",
  "$(length(unexecuted_edges(ms, d))) of them unexecuted.")
s = solver_settings(d)
p("Solver recorded on the driver: `$(s.solver)`, abstol $(s.abstol), reltol $(s.reltol). ",
  "Drain every $(d.drain_interval) s, rounding `$(d.rounding.policy)`.")
p()

odes = reduce(vcat, [states(m) for m in ms if formalism(m) === :ode])
oi(sp) = findfirst(==(sp), odes)
jumps = reduce(vcat, [states(m) for m in ms if formalism(m) === :jump])
tlm = only(m for m in ms if m isa CoreATranslation)
toff = findfirst(==(first(states(tlm))), jumps) - 1
ngene = length(tlm.genes)

# Phase 11's fold-change definition, kept so the two readings compare: each
# gene's count, with ptsG's cytoplasmic pool added back, over its count after
# the first handshake.
function folds(u0, u1)
    p0 = u0[toff .+ (1:ngene)]
    p1 = collect(Float64, u1[toff .+ (1:ngene)])
    ip = findfirst(g -> g.locus === TL_PTSG, tlm.genes)
    p1[ip] += u1[toff + ngene + 1] - u0[toff + ngene + 1]
    return p1 ./ p0
end

Random.seed!(SEED)
twarm = @elapsed handshake_step!(d)
u0 = copy(d.jump.u)
track = (:M_atp_c, :M_gtp_c, :M_trna_c, :M_trna_chg_c)
traj = Dict(sp => Float64[] for sp in track)
lo = Dict(sp => d.ode.u[oi(sp)] for sp in track)
first_clip = Dict{Symbol, Float64}()
nclip = Dict{Symbol, Int}()
floor_at_rebuild = 0         # rebuild instants with under one charged-tRNA particle
trun = @elapsed for k in 2:CYCLE
    handshake_step!(d)
    if k % d.steps_per_drain == 0
        for b in d.debits
            b.deficit > 0 || continue
            nclip[b.counter] = get(nclip, b.counter, 0) + 1
            haskey(first_clip, b.counter) || (first_clip[b.counter] = d.ode.t)
        end
    end
    for sp in track
        lo[sp] = min(lo[sp], d.ode.u[oi(sp)])
    end
    if k % 60 == 0
        for sp in track
            push!(traj[sp], d.ode.u[oi(sp)])
        end
        d.ode.u[oi(:M_trna_chg_c)] * d.factor < 1 && (global floor_at_rebuild += 1)
    end
end
@assert d.ode.t == COREA_CYCLE_S

percycle = twarm + trun
p("The cycle completed: t = $(d.ode.t) s after $(d.n_handshakes) handshakes, ",
  "with no solver failure (the hook throws on one).")
p()
p("## 13.7 — wall-clock per trajectory")
p()
p(@sprintf("Build %.1f s; first handshake (compiles) %.1f s; the remaining %d handshakes **%.1f s** (%.2f ms each).",
           tbuild, twarm, CYCLE - 1, trun, 1000 * trun / (CYCLE - 1)))
p(@sprintf("A warm trajectory is therefore **%.1f s** of stepping, plus %.1f s to build. A process pays the %.0f s compile once, not per trajectory.",
           trun, tbuild, twarm))
p(@sprintf("Against phase 3's toy extrapolation of %.3f s per cycle that is %.0f× slower; against phase 11's partial seven-module %.1f s (job 17131232, without transcription's counters) it is %.2f×.",
           TOY_S_PER_CYCLE, trun / TOY_S_PER_CYCLE, PHASE11_S_PER_CYCLE, trun / PHASE11_S_PER_CYCLE))
p(@sprintf("One core runs %.0f warm trajectories an hour; 50 calibration replications of a posterior needing E sequential evaluations cost 50·E·%.1f core-seconds, which is K1's input once task 16.2 fixes E (spec §8 K1).",
           3600 / trun, trun))
p()

census = clipping_census(d)
fh = folds(u0, d.jump.u)
g = growth_report(d)
p("## What phase 11's partial run reported, remeasured with every counter and credit")
p()
p(@sprintf("Check 7's census: %d of %d drains clipped (fraction %.4f). Not the K5 score, which is phase 14's.",
           census.clipped, census.drains, census.fraction))
p()
p("| counter | drains clipped | first clip (s) |")
p("|---|---|---|")
for c in unique(b.counter for b in d.debits)
    p(@sprintf("| %s | %d | %s |", c, get(nclip, c, 0),
               haskey(first_clip, c) ? @sprintf("%.0f", first_clip[c]) : "never"))
end
p()
p("Minimum over the cycle, and every 60 s, first and last five samples (mM):")
p()
for sp in track
    v = traj[sp]
    p(@sprintf("- `%s`: min %.4g (%.0f particles at the final volume); ", sp, lo[sp], lo[sp] * d.factor),
      join((@sprintf("%.4f", x) for x in v[1:5]), ", "), " … ",
      join((@sprintf("%.4f", x) for x in v[end-4:end]), ", "))
end
p()
p("R11: the charged pool held under one particle at $floor_at_rebuild of ",
  "$(length(traj[:M_trna_chg_c])) rebuild instants.")
p()
p(@sprintf("Protein fold change (phase 11's definition): median **%.3f**, min %.3f, max %.3f. Phase 11's partial run gave 1.497; §3's band [1.7, 2.3] is phase 14's F5 to judge.",
           median(fh), minimum(fh), maximum(fh)))
p(@sprintf("Fractional growth %.4f.", g.fractional))
p()
p("## What is ours in this run")
p()
p("```")
p(reduction_report(ms, d))
p("```")

write(joinpath(@__DIR__, "corea_full_cycle_result.md"), String(take!(out)))
println("wrote dev/scripts/corea_full_cycle_result.md")
