# Spec §11 task 13.4: D10's drain-granularity measurement at full scale.
#
# The assembled Core A′ (`build_corea()`) over one 6,300 s cycle under 1 s, 5 s
# and 60 s drain granularity, compared on every ODE pool. The method is phase
# 4's (`dev/scripts/rebuild_channel.jl`, whose header says why), and two of its
# rules are what make the number mean anything:
#
# - **Paired ensembles.** Coarsening the drain changes how often the hook
#   clears the counters and so how often the SSA's aggregation is rebuilt,
#   which consumes randomness: one seed gives three paths. Each seed runs at
#   every granularity, and the difference is taken per seed.
# - **Drain-aligned instants.** Between drains a coarse configuration holds up
#   to `drain − 1` s of unpaid cost, so its debited pools sit high by that
#   bookkeeping offset. Every 60 s is a multiple of all three drains, so there
#   each configuration has just paid the same accrual. The pre-drain sawtooth
#   is reported separately, on the debited pools, one handshake before the
#   final aligned instant.
#
# Reported per (drain, pool): the paired relative difference at the final
# aligned instant with its standard error, and the maximum over that pool's
# 105 instants with the instant it came from. D10's rule is on the observed
# pools: below one percent in every one, the coarser drain may be used. A pool
# whose base mean is under one particle has no meaningful relative difference
# and is listed apart.
#
# Usage: SEEDS=50 julia --project dev/scripts/drain_granularity.jl
# Regenerate: sbatch dev/scripts/drain_granularity.slurm

using InferCell
using Random
using Printf
using Dates
using Statistics: mean, std

const COMMIT = strip(read(`git rev-parse --short HEAD`, String))
const DIRTY = !isempty(strip(read(`git status --porcelain -- src test dev/scripts`, String)))
const JOB = get(ENV, "SLURM_JOB_ID", "none")
const SEEDS = parse(Int, get(ENV, "SEEDS", "50"))
const DRAINS = (1.0, 5.0, 60.0)
const CYCLE = round(Int, COREA_CYCLE_S)
const ALIGN = 60
const NALIGN = CYCLE ÷ ALIGN
const D10_THRESHOLD = 0.01

const ODES = reduce(vcat, [states(m) for m in corea_models() if formalism(m) === :ode])
const NODE = length(ODES)

# Per seed: every ODE pool at each aligned instant and one handshake before the
# last one, and the trajectory's wall-clock.
function ensemble(drain)
    aligned = zeros(SEEDS, NALIGN, NODE)
    predrain = zeros(SEEDS, NODE)
    walls = zeros(SEEDS)
    for s in 1:SEEDS
        Random.seed!(130_400 + s)
        d = build_corea(drain_interval = drain)
        walls[s] = @elapsed out = run_handshake!(d, CYCLE)
        for i in 1:NALIGN
            aligned[s, i, :] = out.ode[i * ALIGN]
        end
        predrain[s, :] = out.ode[CYCLE - 1]
        s % 10 == 0 && (println("  drain $drain s: seed $s of $SEEDS, ",
                                @sprintf("%.1f s", walls[s])); flush(stdout))
    end
    return (aligned = aligned, predrain = predrain, walls = walls)
end

function paired(a, b)
    denom = mean(b; dims = 1)
    rel = (a .- b) ./ denom
    return dropdims(mean(rel; dims = 1); dims = 1),
           dropdims(std(rel; dims = 1); dims = 1) ./ sqrt(SEEDS),
           dropdims(denom; dims = 1)
end

println("Drain granularity at full scale: $SEEDS seeds × $(length(DRAINS)) drains"); flush(stdout)
runs = Dict(drain => ensemble(drain) for drain in DRAINS)
base = runs[1.0]
factor = corea_particles_per_mM()     # the initial volume: only the floor test reads it

# The pools the hook debits or credits, read from the lowered records.
probe = build_corea(tspan = (0.0, 60.0))
debited = sort(unique(b.species for b in probe.debits if b.pool_idx > 0))

out = IOBuffer()
p(args...) = (println(out, args...); println(args...); flush(stdout))
p("# Drain granularity at full scale (spec task 13.4)")
p()
p("Generated by `dev/scripts/drain_granularity.jl` at commit $COMMIT",
  DIRTY ? " (tree dirty)" : "", ", Slurm job $JOB, on $(gethostname()), ",
  "$(now()), Julia $VERSION.")
p()
p("Regenerate with `sbatch dev/scripts/drain_granularity.slurm`.")
p()
p("`build_corea()` over one $CYCLE s cycle, $SEEDS paired seeds per granularity, every one of the $NODE ODE pools sampled at the $NALIGN drain-aligned instants (every $ALIGN s).")
p()
for drain in DRAINS
    w = runs[drain].walls
    p(@sprintf("- %4.0f s drain: warm trajectory %.1f s mean (min %.1f, max %.1f).",
               drain, mean(w[2:end]), minimum(w[2:end]), maximum(w[2:end])))
end
p()

verdicts = Dict{Float64, Bool}()
for drain in DRAINS[2:end]
    e = runs[drain]
    m, se, denom = paired(e.aligned, base.aligned)
    floored = [j for j in 1:NODE if minimum(denom[:, j]) * factor < 1]
    rows = NamedTuple[]
    for j in 1:NODE
        j in floored && continue
        k = argmax(abs.(m[:, j]))
        push!(rows, (pool = ODES[j], final = m[end, j], final_se = se[end, j],
                     max = m[k, j], max_se = se[k, j], max_t = k * ALIGN))
    end
    sort!(rows; by = r -> -abs(r.final))
    worst = first(rows)
    verdicts[drain] = all(r -> abs(r.final) < D10_THRESHOLD, rows)

    p("## $(Int(drain)) s against the published 1 s drain")
    p()
    p(@sprintf("Largest |final| paired relative difference over the %d pools compared: **%+.3g%%** (± %.2g%%) on `%s`, selected from %d pools. D10 verdict: **%s**.",
               length(rows), 100 * worst.final, 100 * worst.final_se, worst.pool, length(rows),
               verdicts[drain] ? "below 1% in every pool" : "above 1% in at least one pool"))
    isempty(floored) || p("Under one particle in the base mean at some instant, so not compared: ",
                          join(("`$(ODES[j])`" for j in floored), ", "), ".")
    p()
    p("| pool | final (t = $CYCLE s) | ± SE | max over $NALIGN instants | ± SE | at t (s) |")
    p("|---|---|---|---|---|---|")
    for r in rows
        p(@sprintf("| %s | %+.3g%% | %.2g%% | %+.3g%% | %.2g%% | %d |", r.pool,
                   100 * r.final, 100 * r.final_se, 100 * r.max, 100 * r.max_se, r.max_t))
    end
    p()
    pm, pse, _ = paired(reshape(e.predrain, SEEDS, 1, NODE),
                        reshape(base.predrain, SEEDS, 1, NODE))
    p("Sawtooth, one handshake before the final drain (t = $(CYCLE - 1) s), on the debited pools — a bookkeeping offset of up to $(Int(drain) - 1) s of unpaid cost, not dynamics:")
    p()
    for sp in debited
        j = findfirst(==(sp), ODES)
        p(@sprintf("- `%s`: %+.3g%% ± %.2g%%", sp, 100 * pm[1, j], 100 * pse[1, j]))
    end
    p()
end

p("## Verdict")
p()
coarsest = maximum([dr for dr in DRAINS[2:end] if verdicts[dr]]; init = 1.0)
p(coarsest == 1.0 ?
  "Neither coarser drain passes D10's one-percent rule, so the published 1 s drain stays, and no reduction is registered for it." :
  "The coarsest drain passing D10's one-percent rule in every compared pool is **$(Int(coarsest)) s**. Registering it is a labelled reduction whose measured cost is the largest final difference above.")

write(joinpath(@__DIR__, "drain_granularity_result.md"), String(take!(out)))
println("wrote dev/scripts/drain_granularity_result.md")
