# Generate the seeded SSA reference for spec/spec.md §11 task 2.6.
#
# Builds the two single-module jump models, seeds the default RNG, solves each
# with SSAStepper at the save points below and writes the integer initial
# condition, the parameter vector (as UInt64 bit patterns), the save times and
# every saved state. A JumpProblem saves at every event by default as well as
# at `saveat`, so the reference holds the full event record — every jump time
# and every count — not a 21-point subsample. `test/test_jump_composition.jl` re-solves under the same
# seed and asserts equality element for element, so a change to the jump path
# that alters a single count — or the order in which the reactions are
# registered, which changes how the random stream is consumed — is caught.
#
# First generated on the tree before phase 2 changed the `reactions` contract
# (the commit named in the output header, whose src/ equals the merge base),
# through `dev/scripts/make_ssa_reference.slurm`, which runs this twice and
# diffs the two files to show the result is deterministic on the partition it
# ran on. Any tree whose jump path is unchanged reproduces the body byte for
# byte. What legitimately invalidates it is a change to the random stream —
# a JumpProcesses bump that alters Direct's sampling order, or a Julia release
# that changes integer seeding — so if test 2.6 fails after a Manifest or
# Julia change, rerun the slurm script rather than reading it as a regression.
#
# Usage: julia --project dev/scripts/make_ssa_reference.jl <output path>

using InferCell
using JumpProcesses: SSAStepper
using Random
using Dates

const SEED = 20260904
const TSPAN = (0.0, 50.0)
const SAVEAT = 0.0:2.5:50.0

# Default constructors: the fixture pins the models as shipped, not a tuned case.
const MODELS = [("SGE", StochasticGeneExpression()), ("BGE", BurstyGeneExpression())]

out = only(ARGS)
commit = strip(read(`git rev-parse --short HEAD`, String))
dirty = !isempty(strip(read(`git status --porcelain -- src test/runtests.jl Project.toml Manifest.toml`, String)))

bits(v) = reinterpret(UInt64, collect(Float64, v))
fmtbits(v) = "UInt64[" * join(("0x" * string(b; base = 16, pad = 16) for b in bits(v)), ", ") * "]"
fmtint(v) = "Int[" * join(string.(v), ", ") * "]"

open(out, "w") do io
    println(io, "# Seeded SSA reference for the single-module jump path.")
    println(io, "# Generated by dev/scripts/make_ssa_reference.jl. Do not edit by hand.")
    println(io, "# Source commit: $commit", dirty ? " (WARNING: src/ or manifest dirty at generation)" : "")
    println(io, "# Stepper: SSAStepper, Random.seed!($SEED) before each solve, tspan = $TSPAN, saveat = $SAVEAT")
    println(io, "# Default save_positions, so every jump is saved as well as the saveat points.")
    println(io, "# Valid while the random stream is unchanged; a JumpProcesses or Julia RNG change")
    println(io, "# invalidates it legitimately — rerun dev/scripts/make_ssa_reference.slurm.")
    println(io, "# Julia $(VERSION) on $(gethostname()), $(Dates.now())")
    println(io, "# Counts are Int; parameters are Float64 bit patterns, reinterpret(Float64, ·) recovers them.")
    println(io)
    println(io, "const SSA_REFERENCE_COMMIT = \"$commit\"")
    println(io, "const SSA_REFERENCE_SEED = $SEED")
    println(io, "const SSA_REFERENCE_TSPAN = $TSPAN")
    println(io, "const SSA_REFERENCE_SAVEAT = $(repr(SAVEAT))")
    for (name, m) in MODELS
        prob = build_problem(m; tspan = TSPAN)
        Random.seed!(SEED)
        sol = solve(prob, SSAStepper(); saveat = SAVEAT)
        println(io)
        println(io, "const SSA_REFERENCE_$(name)_U0 = ", fmtint(prob.prob.u0))
        println(io, "const SSA_REFERENCE_$(name)_P_BITS = ", fmtbits(prob.prob.p))
        println(io, "const SSA_REFERENCE_$(name)_T_BITS = ", fmtbits(sol.t))
        println(io, "const SSA_REFERENCE_$(name)_U = [")
        for u in sol.u
            println(io, "    ", fmtint(u), ",")
        end
        println(io, "]")
        println("$name: $(length(sol.t)) save points, retcode $(sol.retcode), final state $(sol.u[end])")
    end
end

println("wrote $out at commit $commit")
