# Generate the byte-identity reference for spec/spec.md §11 task 1.2.
#
# Builds `build_problem(TranscriptionTranslation(); tspan=(0.0, 50.0))`, solves
# it with Tsit5 at the tolerances pinned below, and writes the initial
# condition, the parameter vector, the save times and every saved state as
# UInt64 bit patterns. The test `test/test_reference_trajectory.jl` reinterprets
# those bits and asserts equality bit for bit, so a change to the orchestrator
# that alters even the sign of a zero is caught.
#
# Run on the unchanged tree (the commit named in the output header) through
# `dev/scripts/make_txl_reference.slurm`, which runs this twice and diffs the
# two files to show the result is deterministic on the partition it ran on.
#
# Usage: julia --project dev/scripts/make_txl_reference.jl <output path>

using InferCell
using OrdinaryDiffEq: Tsit5, solve
using Dates

const SAVEAT = 0.0:2.5:50.0
const ABSTOL = 1e-6   # OrdinaryDiffEq's defaults, pinned explicitly so a
const RELTOL = 1e-3   # default change upstream cannot silently move the fixture

out = only(ARGS)
commit = strip(read(`git rev-parse --short HEAD`, String))
dirty = !isempty(strip(read(`git status --porcelain -- src test/runtests.jl Project.toml Manifest.toml`, String)))

prob = build_problem(TranscriptionTranslation(); tspan = (0.0, 50.0))
sol = solve(prob, Tsit5(); saveat = SAVEAT, abstol = ABSTOL, reltol = RELTOL)

bits(v) = reinterpret(UInt64, collect(Float64, v))
fmt(v) = "UInt64[" * join(("0x" * string(b; base = 16, pad = 16) for b in bits(v)), ", ") * "]"

open(out, "w") do io
    println(io, "# Byte-identity reference for build_problem(TranscriptionTranslation()).")
    println(io, "# Generated by dev/scripts/make_txl_reference.jl. Do not edit by hand.")
    println(io, "# Source commit: $commit", dirty ? " (WARNING: src/ or manifest dirty at generation)" : "")
    println(io, "# Solver: Tsit5, saveat = $(SAVEAT), abstol = $ABSTOL, reltol = $RELTOL")
    println(io, "# Julia $(VERSION) on $(gethostname()), $(Dates.now())")
    println(io, "# Values are Float64 bit patterns; reinterpret(Float64, ·) recovers them.")
    println(io)
    println(io, "const TXL_REFERENCE_COMMIT = \"$commit\"")
    println(io, "const TXL_REFERENCE_SAVEAT = $(repr(SAVEAT))")
    println(io, "const TXL_REFERENCE_ABSTOL = $ABSTOL")
    println(io, "const TXL_REFERENCE_RELTOL = $RELTOL")
    println(io, "const TXL_REFERENCE_U0_BITS = ", fmt(prob.u0))
    println(io, "const TXL_REFERENCE_P_BITS = ", fmt(prob.p))
    println(io, "const TXL_REFERENCE_T_BITS = ", fmt(sol.t))
    println(io, "const TXL_REFERENCE_U_BITS = [")
    for u in sol.u
        println(io, "    ", fmt(u), ",")
    end
    println(io, "]")
end

println("wrote $out: $(length(sol.t)) save points, retcode $(sol.retcode), commit $commit")
