# Spec §11 tasks 11.7 and 11.10: whether translation's charged-tRNA counter
# can clip, the charged-pool elasticity of the translation constant, and the
# protein fold change over a cycle.
#
# 11.7. Check 7's census on the tRNA counter, over a full 6,300 s cycle, at
#       each of phase 9's pool sizes. It feeds task 9.8's scan, whose check 7
#       half was deferred here: 9.8 gave the analytic buffer, and this gives
#       the census with translation itself as the consumer. Composition:
#       NucleotideRecycling + HeldGlycolytic + TrnaCharging + live transcripts
#       (transcription and decay stripped of every counter and edge) +
#       CoreATranslation carrying only the tRNA counter, so the census counts
#       that counter and nothing else. The pool's k_chg is re-derived for each
#       pool, as D14 does.
#
# 11.10. The elasticity is analytic (`translation_elasticity`), checked against
#       a central difference through the module's own `rate_constants`. The
#       fold change is measured three ways: jump-only (transcription, decay
#       and translation at the nominal charged pool, eight seeds), in the full
#       seven-module hybrid (one seed, every counter), and analytically as
#       1 + k·m̄·T/P₀ at the measured transcript means. The hybrid run also
#       reports when each counter first clips and the wall-clock per cycle.
#
# Usage: julia --project dev/scripts/translation_diagnostics.jl
# Regenerate: sbatch dev/scripts/translation_diagnostics.slurm

using InferCell
using JumpProcesses: SSAStepper
using SciMLBase: solve
using Printf
using Dates
using Random
using Statistics: mean, median

include(joinpath(@__DIR__, "..", "..", "test", "nucleotide_test_models.jl"))

const COMMIT = strip(read(`git rev-parse --short HEAD`, String))
const DIRTY = !isempty(strip(read(`git status --porcelain -- src test dev/scripts`, String)))
const JOB = get(ENV, "SLURM_JOB_ID", "none")
const CYCLE = 6300
const N = corea_particles_per_mM()
const POOLS = [0.025, 0.05, 0.1, 0.125, 0.25, 0.5, 1.0]
const genes = read_transcription_genes()
const res = [read_translation_residues()[g.locus] for g in genes]

birth_death() = AbstractSubModel[
    CoreATranscription(counters = (), edges = CouplingEdge[], rebuilt = Symbol[]),
    CoreATranscriptDecay(counters = ())]
idx(ms, s, f) = findfirst(==(s), reduce(vcat, [states(m) for m in ms if formalism(m) === f]))
const TRNA_ONLY = [c for c in TRANSLATION_COUNTERS if c.counter === :tRNA_translat]

out = IOBuffer()
p(args...) = (println(out, args...); println(args...); flush(stdout))

p("# Translation diagnostics (spec tasks 11.7, 11.10)")
p()
p("Generated by `dev/scripts/translation_diagnostics.jl` at commit $COMMIT",
  DIRTY ? " (tree dirty)" : "", ", Slurm job $JOB, on $(gethostname()), ",
  "$(now()), Julia $VERSION.")
p()
p("Regenerate with `sbatch dev/scripts/translation_diagnostics.slurm`.")
p()

# ---------------------------------------------------------------------------
# 11.7 — check 7's census on the charged-tRNA counter, per pool size
# ---------------------------------------------------------------------------

p("## 11.7 — check 7's census on the charged-tRNA counter")
p()
p("One full cycle (6,300 handshakes, 1 s drain) per pool, charged fraction 0.8,")
p("`k_chg` re-derived per pool (D14). Translation carries only `tRNA_translat`,")
p("so the census counts that counter alone. \"Clipped\" is drains at which the")
p("counter carried a deficit; \"min charged\" is the charged pool's minimum over")
p("the cycle, in particles, at handshake resolution; \"buffer\" is the charged")
p("pool at cycle end over the cycle's mean residue flux.")
p()
p("| pool (mM) | clipped / drains | final deficit | min charged | steady charged fraction | residues/s | buffer (s) | wall (s) |")
p("|---|---|---|---|---|---|---|---|")
census_rows = []
for pool in POOLS
    ms = AbstractSubModel[NucleotideRecycling(), HeldGlycolytic(),
                          TrnaCharging(pool_mM = pool), birth_death()...,
                          CoreATranslation(counters = TRNA_ONLY)]
    d = build_problem(ms; tspan = (0.0, float(CYCLE)))
    iu, ic = idx(ms, :M_trna_c, :ode), idx(ms, :M_trna_chg_c, :ode)
    tl = ms[end]
    off = sum(length(states(m)) for m in ms if formalism(m) === :jump) - length(states(tl))
    u0 = d.jump.u[off .+ (1:length(states(tl)))]
    Random.seed!(1107)
    wall = @elapsed rec = run_handshake!(d, CYCLE)
    c = clipping_census(d)
    chg = [u[ic] for u in rec.ode]
    frac = [u[ic] / (u[iu] + u[ic]) for u in rec.ode]
    made = proteins_made(tl, u0, d.jump.u[off .+ (1:length(states(tl)))])
    flux = sum(made .* res) / CYCLE
    buffer = chg[end] * d.factor / flux
    push!(census_rows, (; pool, clipped = c.clipped, drains = c.drains, flux, buffer,
                        minchg = minimum(chg) * d.factor))
    p(@sprintf("| %.3f | %d / %d | %.1f | %.0f | %.4f | %.1f | %.2f | %.1f |",
               pool, c.clipped, c.drains, sum(c.deficits), minimum(chg) * d.factor,
               mean(frac[end-599:end]), flux, buffer, wall))
end
p()
clear = [r.pool for r in census_rows if r.clipped == 0]
p("Pools with zero clips over the cycle: ", isempty(clear) ? "none" :
  join((@sprintf("%.3f", x) for x in clear), ", "), " mM. ",
  "Check 1b's floor (task 9.8) needs at least 0.125 mM at 0.8 charged.")
p()

# ---------------------------------------------------------------------------
# 11.10 — the elasticity
# ---------------------------------------------------------------------------

tl = CoreATranslation()
chg0 = 0.2
e = [translation_elasticity(g.length, r, chg0) for (g, r) in zip(genes, res)]
h = 1e-6
fd = let k(c) = rate_constants(Float64[], 0.0, tl, [c])
    (log.(k(chg0 * exp(h))) .- log.(k(chg0 * exp(-h)))) ./ 2h
end
whole = [begin
             c = chg0
             a = (1 + RIBO_K0 / (RIBOSOME_COPIES / N)) * RIBO_KD^2 / c^2
             b = r * RIBO_KD / c
             (2a + b) / (a + b + r)
         end for r in res]
p("## 11.10 — the charged-pool elasticity of the translation constant")
p()
p(@sprintf("At the nominal 0.2 mM charged pool, `∂ ln k / ∂ ln [M_trna_chg_c]` spans **%.4f to %.4f** across the seventeen genes (median %.4f).",
           minimum(e), maximum(e), median(e)))
p(@sprintf("A central difference through `rate_constants` agrees to %.1e relative.", maximum(abs.(fd .- e) ./ e)))
p(@sprintf("Transcription's four-pool elasticity is 0.0437 to 0.0506 (task 10.8), so this reverse channel is about %.1f× stronger.", median(e) / 0.047))
p(@sprintf("Had the whole pool stood in for each per-amino-acid pool, it would be %.4f to %.4f (§12, 2026-09-24).", minimum(whole), maximum(whole)))
p()

# ---------------------------------------------------------------------------
# 11.10 — the fold change, jump-only
# ---------------------------------------------------------------------------

function folds(u0, u1, tlm)
    n = length(tlm.genes)
    p0 = u0[1:n]
    p1 = u1[1:n] .+ 0
    ip = findfirst(g -> g.locus === TL_PTSG, tlm.genes)
    p1 = collect(Float64, p1); p1[ip] += u1[n + 1] - u0[n + 1]
    return p1 ./ p0
end

jo = Vector{Vector{Float64}}()
wall_jo = 0.0
for seed in 1:8
    ms = AbstractSubModel[CoreATranscription(seed = seed), CoreATranscriptDecay(), CoreATranslation()]
    Random.seed!(seed)
    t = @elapsed sol = solve(build_problem(ms; tspan = (0.0, float(CYCLE))), SSAStepper();
                             saveat = float(CYCLE))
    global wall_jo += t
    off = sum(length(states(m)) for m in ms[1:2])
    n = length(states(ms[3]))
    push!(jo, folds(sol.u[1][off .+ (1:n)], sol.u[end][off .+ (1:n)], ms[3]))
end
fjo = [mean(f[i] for f in jo) for i in 1:17]

ks = last.(translation_rate_constants(tl))
fan = [1 + ks[i] * genes[i].mean_mrna * CYCLE / genes[i].ptn_count for i in 1:17]

slope(f) = let x = log.([g.length for g in genes]), y = log.(f)
    sum((x .- mean(x)) .* (y .- mean(y))) / sum((x .- mean(x)) .^ 2)
end

p("## 11.10 — protein fold change over one cycle")
p()
p("§3's external check 2 asks for a median in [1.7, 2.3], no gene below 1.5 or above 3.0, and a negative fold-versus-length slope (long genes underproduce).")
p()
p("| gene | length | residues | P₀ | fold, jump-only (mean of 8) | fold, analytic |")
p("|---|---|---|---|---|---|")
for (i, g) in enumerate(genes)
    p(@sprintf("| %s (%s) | %d | %d | %d | %.3f | %.3f |", g.locus, g.reaction,
               g.length, res[i], g.ptn_count, fjo[i], fan[i]))
end
p()
p(@sprintf("Jump-only: median **%.3f**, min %.3f, max %.3f, log-log slope against length %.3f. %d of 17 below 1.5.",
           median(fjo), minimum(fjo), maximum(fjo), slope(fjo), count(<(1.5), fjo)))
p(@sprintf("Analytic, 1 + k·m̄·T/P₀ at the measured transcript means: median %.3f, min %.3f, max %.3f.",
           median(fan), minimum(fan), maximum(fan)))
# The diagnosis: which knob would it take.
need = median(fan .- 1)
p(@sprintf("For the median to reach 2 the median of k·m̄·T/P₀ must reach 1 from %.3f, a factor of %.2f.", need, 1 / need))
p(@sprintf("`k` is proportional to `riboKcat` (the denominator does not contain it), so that is riboKcat ≈ %.1f rather than 12.", 12 / need))
ks_ss = [translation_rate_constant(g.length, r, 0.2 * 0.95) for (g, r) in zip(genes, res)]
p(@sprintf("The charged pool is not what holds it back: at the nominal pool the elasticity is %.3f, so a 5%% lower charged pool moves each constant by %.2f%%.",
           median(e), 100 * median(1 .- ks_ss ./ ks)))
p()

# ---------------------------------------------------------------------------
# The full seven-module hybrid, one cycle
# ---------------------------------------------------------------------------

ms = AbstractSubModel[CentralGlycolysis(enzymes = :translated), PtsTransport(),
                      NucleotideRecycling(enzymes = :translated), TrnaCharging(),
                      birth_death()..., CoreATranslation()]
tbuild = @elapsed d = build_problem(ms; tspan = (0.0, float(CYCLE)))
Random.seed!(1110)
twarm = @elapsed handshake_step!(d)
tlm = ms[end]
off = sum(length(states(m)) for m in ms if formalism(m) === :jump) - length(states(tlm))
nstl = length(states(tlm))
u0 = copy(d.jump.u[off .+ (1:nstl)])      # after one handshake: no protein has moved much
first_clip = Dict{Symbol, Float64}()
nclip = Dict{Symbol, Int}()
odes = reduce(vcat, [states(m) for m in ms if formalism(m) === :ode])
oi(s) = findfirst(==(s), odes)
track = (:M_atp_c, :M_gtp_c, :M_trna_c, :M_trna_chg_c)
traj = Dict(s => Float64[] for s in track)
trun = @elapsed for k in 2:CYCLE
    handshake_step!(d)
    for b in d.debits
        if b.deficit > 0
            nclip[b.counter] = get(nclip, b.counter, 0) + 1
            haskey(first_clip, b.counter) || (first_clip[b.counter] = d.ode.t)
        end
    end
    k % 60 == 0 && for s in track
        push!(traj[s], d.ode.u[oi(s)])
    end
end
fh = folds(u0, d.jump.u[off .+ (1:nstl)], tlm)
g = growth_report(d)

p("## The full seven-module hybrid, one cycle")
p()
p("`CentralGlycolysis(:translated)` + `PtsTransport` + `NucleotideRecycling(:translated)` + `TrnaCharging` + live transcripts + `CoreATranslation` with every counter. One seed.")
p()
p(@sprintf("Wall-clock: build %.1f s, first handshake (compiles) %.1f s, the remaining %d handshakes **%.1f s** (%.2f ms each).",
           tbuild, twarm, CYCLE - 1, trun, 1000 * trun / (CYCLE - 1)))
p(@sprintf("Fold change: median %.3f, min %.3f, max %.3f. Fractional growth %.4f.",
           median(fh), minimum(fh), maximum(fh), g.fractional))
p()
p("| counter | drains clipped | first clip (s) |")
p("|---|---|---|")
for c in unique(b.counter for b in d.debits)
    p(@sprintf("| %s | %d | %s |", c, get(nclip, c, 0),
               haskey(first_clip, c) ? @sprintf("%.0f", first_clip[c]) : "never"))
end
p()
p("Pools every 60 s, first and last five samples (mM):")
p()
for s in track
    v = traj[s]
    p("- `$s`: ", join((@sprintf("%.4f", x) for x in v[1:5]), ", "), " … ",
      join((@sprintf("%.4f", x) for x in v[end-4:end]), ", "))
end
p()

write(joinpath(@__DIR__, "translation_diagnostics_result.md"), String(take!(out)))
println("wrote dev/scripts/translation_diagnostics_result.md")
